name: Create Release Candidate

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: "Commit ID"
        required: true
      version:
        description: "Version (e.g. v1.0.0-rc.1)"
        required: true
  push: 

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_id }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ github.event.inputs.version }}
          name: Release Candidate ${{ github.event.inputs.version }}
          generate_release_notes: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
